defaults:
  - model: asvspoof_lcnn
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

data_dir: data/LA

max_length: 77870

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
  betas: [0.9, 0.999]
  eps: 1e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 31730

loss_function:
  _target_: src.loss.ASVSpoofCELoss
  weight: [1.0, 9.0]

trainer:
  log_step: 100
  n_epochs: 15
  epoch_len: 3173
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: true
  monitor: "min val_eer" 
  save_period: 1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1